name: Build and push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-java:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    strategy:
      matrix:
        version: [8, 11, 17]
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create the Java ${{ matrix.version }} builder image
        # we still can't add linux/arm64/v8 because of a segfault on yarn installation on 20.04
        run: |
          docker buildx build \
          --platform linux/amd64,linux/arm64/v8 \
          -f Dockerfiles/java-${{ matrix.version }}/build/Dockerfile \
          -t metabase/ci:java-${{ matrix.version }}-clj-1.11.0.1100.04-2022-build --push --compress --no-cache .
      - name: Create the Java ${{ matrix.version }} testing image
        # there are no arm64 versions of the browsers
        run: |
          docker buildx build \
          --platform linux/amd64 \
          -f Dockerfiles/java-${{ matrix.version }}/test/Dockerfile \
          -t metabase/ci:java-${{ matrix.version }}-clj-1.11.0.1100.04-2022-node-browsers --push --compress --no-cache .
