name: Build and push to Dockerhub

on:
  push:
    branches:
      - master

jobs:
  build-java-8:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create mongo 4 container image
        run: docker buildx build -f java-8/Dockerfile -t paoliniluis/ci:java-8-clj-1.10.1040.12-2021-node-browsers --push --compress --no-cache.
    
  build-java-11:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create mssql 2019 image
        run: docker buildx build -f java-11/Dockerfile -t paoliniluis/ci:java-11-clj-1.10.1040.12-2021-node-browsers --push --compress --no-cache .

  build-java-17:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create mysql 5.7 image
        run: docker buildx build -f java-17/Dockerfile -t paoliniluis/ci:java-17-clj-1.10.1040.12-2021-node-browsers --push --compress --no-cache .